# Generated by Django 4.1.7 on 2023-03-31 12:21

from django.db import migrations, models
import django.db.models.deletion
import web_app.models
 

class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLivingFacility',
            fields=[
                ('Facility_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Facility_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.activelivingfacility')),
            ],
        ),
        migrations.CreateModel(
            name='HoursReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tracked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_hours', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UCID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Ucalgary_email', models.EmailField(max_length=254)),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorksAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.activelivingfacility')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.attendant')),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility', models.CharField(max_length=50)),
                ('Check_in_time', models.DateTimeField(editable=False)),
                ('Check_out_time', models.DateTimeField(editable=False)),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.AddField(
            model_name='tracked',
            name='UCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.user'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.CreateModel(
            name='Oversees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tracked_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
                ('Verifier_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.verifier')),
            ],
        ),
        migrations.CreateModel(
            name='LooksAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.hoursreport')),
                ('Tracked_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
                ('Verifier_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.verifier')),
            ],
        ),
        migrations.CreateModel(
            name='Intramurals',
            fields=[
                ('Intramural_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Intramural_team', models.CharField(max_length=50)),
                ('Facility_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.activelivingfacility')),
            ],
        ),
        migrations.AddField(
            model_name='hoursreport',
            name='UCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked'),
        ),
        migrations.CreateModel(
            name='FacilityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.activelivingfacility')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Cost', models.FloatField(validators=[web_app.models.validatePositive])),
                ('Facility_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.activelivingfacility')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_classes', models.PositiveIntegerField()),
                ('Class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.class')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.CreateModel(
            name='DinosMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinos_team', models.CharField(max_length=100)),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompetesIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intramural_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.intramurals')),
                ('TRACKED', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinos_team', models.CharField(max_length=50)),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.verifier')),
            ],
        ),
        migrations.CreateModel(
            name='ChecksIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendant_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.attendant')),
                ('Tracked_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='UCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.user'),
        ),
        migrations.CreateModel(
            name='ApplicationReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.hoursreport')),
                ('Tracked_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
                ('Verifier_UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.verifier')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.tracked')),
            ],
        ),
    ]
